# Generated by Django 2.0.2 on 2018-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='discription',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(),
        ),
    ]
